// Auto-casts high-conviction rug alerts to Farcaster (@basecapital) via Neynar.
// Runs after each risk tick. Idempotent + rate-limited:
//   - only strong rug signals (score < MAX_SCORE)
//   - only recently-scored verdicts (FRESH_MS) -> no back-spam on first run
//   - per-token cooldown (COOLDOWN_MS) -> never spam the same token
//   - at most MAX_PER_RUN casts per tick
// No-ops cleanly if NEYNAR_* env is absent (e.g. local runs). Never fails the pipeline.
import { writeFileSync, mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { verdicts } from "../src/data/log.js"
import type { AgentVerdict } from "../src/lib/verdict.js"
import { casts as prevCasts } from "../src/data/casts.js"

const MAX_SCORE = 30
const FRESH_MS = 3 * 60 * 60 * 1000
const COOLDOWN_MS = 48 * 60 * 60 * 1000
const MAX_PER_RUN = 3
const APP_URL = (process.env.BASE_CAPITAL_URL ?? "https://base-capital.vercel.app").replace(/\/+$/, "")

async function publishCast(apiKey: string, signerUuid: string, text: string, embedUrl: string) {
	const res = await fetch("https://api.neynar.com/v2/farcaster/cast", {
		method: "POST",
		headers: { "content-type": "application/json", "x-api-key": apiKey },
		body: JSON.stringify({ signer_uuid: signerUuid, text, embeds: [{ url: embedUrl }] }),
	})
	const body = await res.text()
	if (!res.ok) throw new Error("neynar " + res.status + ": " + body.slice(0, 300))
	return body
}

function buildText(v: AgentVerdict): string {
	const flags = v.flags.slice(0, 3).join(", ")
	const flagLine = flags ? "\n\u26a0\ufe0f " + flags : ""
	return (
		"\ud83d\udea8 Base Capital flagged $" + v.symbol + " as LIKELY RUG\n" +
		"Risk score: " + v.score + "/100" + flagLine + "\n\n" +
		"Token: " + v.token + "\n" +
		"Every verdict is staked onchain for accountability. Not financial advice."
	)
}

async function main() {
	const apiKey = process.env.NEYNAR_API_KEY
	const signerUuid = process.env.NEYNAR_SIGNER_UUID
	if (!apiKey || !signerUuid) {
		console.log("cast: NEYNAR_* not set, skipping")
		return
	}
	const now = Date.now()
	const casts: Record<string, string> = { ...prevCasts }

	const candidates: AgentVerdict[] = verdicts
		.filter((v) => v.verdict === "LIKELY_RUG" && v.score < MAX_SCORE)
		.filter((v) => now - new Date(v.ts).getTime() < FRESH_MS)
		.filter((v) => {
			const last = casts[v.token.toLowerCase()]
			return !last || now - new Date(last).getTime() > COOLDOWN_MS
		})
		.sort((a, b) => a.score - b.score)

	const seen = new Set<string>()
	const picks: AgentVerdict[] = []
	for (const v of candidates) {
		const key = v.token.toLowerCase()
		if (seen.has(key)) continue
		seen.add(key)
		picks.push(v)
		if (picks.length >= MAX_PER_RUN) break
	}

	if (picks.length === 0) {
		console.log("cast: no new rug alerts to post")
		return
	}

	let posted = 0
	for (const v of picks) {
		try {
			await publishCast(apiKey, signerUuid, buildText(v), APP_URL)
			casts[v.token.toLowerCase()] = new Date().toISOString()
			posted++
			console.log("cast: posted $" + v.symbol + " (" + v.score + ")")
		} catch (e) {
			console.error("cast: failed $" + v.symbol + ":", (e as Error).message)
		}
	}

	if (posted > 0) {
		const pruned: Record<string, string> = {}
		for (const [k, ts] of Object.entries(casts)) {
			if (now - new Date(ts).getTime() < COOLDOWN_MS) pruned[k] = ts
		}
		const here = dirname(fileURLToPath(import.meta.url))
		const out = resolve(here, "../src/data/casts.ts")
		const content =
			"// Auto-generated by agent/cast.ts. Maps token address -> ISO ts of last Farcaster alert.\n" +
			"// Used for per-token cast cooldown. Do not edit by hand.\n" +
			"export const casts: Record<string, string> = " +
			JSON.stringify(pruned, null, "\t") + "\n"
		mkdirSync(dirname(out), { recursive: true })
		writeFileSync(out, content)
	}
	console.log("cast: done, posted " + posted)
}

main().catch((e) => {
	console.error(e)
	process.exit(0)
})
