// Stable types for the backtest report. Kept separate from backtest.ts because
// backtest.ts is fully regenerated by agent/backtest.ts on every run.
export type BacktestRow = {
  symbol: string
  token: string
  score: number // engine score WITH live simulation (production)
  scoreNoSim: number // engine score WITHOUT simulation (ablation / static engine)
  predicted: "unsafe" | "safe"
  truth: "bad" | "good"
  correct: boolean
  oracleReason: string
  sources?: string[] // v4: independent sources confirming a BAD label
}

export type BacktestMetrics = {
  precision: number
  recall: number
  f1: number
  accuracy: number
}

export type BacktestPoint = { threshold: number } & BacktestMetrics

// v4: Wilson 95% score interval for a proportion.
export type Interval = { lo: number; hi: number }

export type BacktestCI = {
  method: string
  precision: Interval & { n: number }
  recall: Interval & { n: number }
}

// v4: inter-oracle agreement (honeypot.is vs GoPlus), Cohen's kappa.
export type OracleAgreement = {
  raters: string
  n: number
  agree: number
  observed: number
  expected: number
  kappa: number
}

export type BacktestReport = {
  generatedAt: string | null
  oracle: string
  predictionRule: string
  threshold: number
  universe: {
    candidates: number
    labeled: number
    bad: number
    good: number
    skippedUnknown: number
  }
  confusion: { tp: number; fp: number; tn: number; fn: number }
  metrics: BacktestMetrics
  metricsNoSim: BacktestMetrics
  sweep: BacktestPoint[]
  rows: BacktestRow[]
  notes: string[]
  // ---- v4 additions (optional so previously generated reports still type) ----
  positives?: number
  ci?: BacktestCI
  agreement?: OracleAgreement
  groundTruthSources?: string[]
  methodology?: string[]
}
