// Auto-generated by agent/backtest.ts. Do not edit by hand.
// Precision/recall of the risk engine vs an independent honeypot oracle
// (honeypot.is buy/sell simulation). Served read-only by GET /backtest.
import type { BacktestReport } from "./backtest-types.js"

export const backtest: BacktestReport = {
  "generatedAt": "2026-06-28T18:25:27.393Z",
  "oracle": "honeypot.is (buy/sell simulation, chainID 8453)",
  "predictionRule": "predict UNSAFE when risk score < threshold, else SAFE",
  "threshold": 75,
  "universe": {
    "candidates": 39,
    "labeled": 21,
    "bad": 2,
    "good": 19,
    "skippedUnknown": 18
  },
  "confusion": {
    "tp": 2,
    "fp": 3,
    "tn": 16,
    "fn": 0
  },
  "metrics": {
    "precision": 0.4,
    "recall": 1,
    "f1": 0.571,
    "accuracy": 0.857
  },
  "metricsNoSim": {
    "precision": 0,
    "recall": 0,
    "f1": 0,
    "accuracy": 0.762
  },
  "sweep": [
    {
      "threshold": 40,
      "precision": 1,
      "recall": 1,
      "f1": 1,
      "accuracy": 1
    },
    {
      "threshold": 45,
      "precision": 0.667,
      "recall": 1,
      "f1": 0.8,
      "accuracy": 0.952
    },
    {
      "threshold": 50,
      "precision": 0.667,
      "recall": 1,
      "f1": 0.8,
      "accuracy": 0.952
    },
    {
      "threshold": 55,
      "precision": 0.667,
      "recall": 1,
      "f1": 0.8,
      "accuracy": 0.952
    },
    {
      "threshold": 60,
      "precision": 0.667,
      "recall": 1,
      "f1": 0.8,
      "accuracy": 0.952
    },
    {
      "threshold": 65,
      "precision": 0.5,
      "recall": 1,
      "f1": 0.667,
      "accuracy": 0.905
    },
    {
      "threshold": 70,
      "precision": 0.4,
      "recall": 1,
      "f1": 0.571,
      "accuracy": 0.857
    },
    {
      "threshold": 75,
      "precision": 0.4,
      "recall": 1,
      "f1": 0.571,
      "accuracy": 0.857
    },
    {
      "threshold": 80,
      "precision": 0.4,
      "recall": 1,
      "f1": 0.571,
      "accuracy": 0.857
    },
    {
      "threshold": 85,
      "precision": 0.286,
      "recall": 1,
      "f1": 0.444,
      "accuracy": 0.762
    }
  ],
  "rows": [
    {
      "symbol": "cbBTC",
      "token": "0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf",
      "score": 84,
      "scoreNoSim": 84,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "AERO",
      "token": "0x940181a94a35a4569e4529a3cdfb74e38fd98631",
      "score": 88,
      "scoreNoSim": 88,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "DEGEN",
      "token": "0x4ed4e862860bed51a9570b96d89af5e1b0efefed",
      "score": 88,
      "scoreNoSim": 88,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "BRETT",
      "token": "0x532f27101965dd16442e59d40670faf5ebb142e4",
      "score": 90,
      "scoreNoSim": 90,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "VIRTUAL",
      "token": "0x0b3e328455c4059eeb9e3f84b5543f74e24e7e1b",
      "score": 40,
      "scoreNoSim": 37,
      "predicted": "unsafe",
      "truth": "good",
      "correct": false,
      "oracleReason": "sellable"
    },
    {
      "symbol": "cbETH",
      "token": "0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22",
      "score": 84,
      "scoreNoSim": 84,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "Surplus",
      "token": "0xc52aedec3374422d7510e294cfaa90799595cba3",
      "score": 26,
      "scoreNoSim": 96,
      "predicted": "unsafe",
      "truth": "bad",
      "correct": true,
      "oracleReason": "HONEYPOT DETECTED"
    },
    {
      "symbol": "LBM",
      "token": "0x15b15fa54b629c634958e8bd639b2fc8af654974",
      "score": 66,
      "scoreNoSim": 66,
      "predicted": "unsafe",
      "truth": "good",
      "correct": false,
      "oracleReason": "sellable"
    },
    {
      "symbol": "TOSHI",
      "token": "0xac1bd2486aaf3b5c0fc3fd868558b082a531b2b4",
      "score": 100,
      "scoreNoSim": 100,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "KTA",
      "token": "0xc0634090f2fe6c6d75e61be2b949464abb498973",
      "score": 92,
      "scoreNoSim": 92,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "MRBASE",
      "token": "0x1cc629606bc4d1a4b35730ca1d32e905abd43722",
      "score": 85,
      "scoreNoSim": 85,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "TRUEX",
      "token": "0x37dc48106e03ffe932b03bb6d761277db0a6dc29",
      "score": 60,
      "scoreNoSim": 60,
      "predicted": "unsafe",
      "truth": "good",
      "correct": false,
      "oracleReason": "sellable"
    },
    {
      "symbol": "DRB",
      "token": "0x3ec2156d4c0a9cbdab4a016633b7bcf6a8d68ea2",
      "score": 100,
      "scoreNoSim": 100,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "PRXVT",
      "token": "0x4b5d32a07b8d3ec5d6928caa30196f8dd6a7c5a9",
      "score": 100,
      "scoreNoSim": 100,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "LFI",
      "token": "0x3722264ab15a1dfce5a5af89e6547f7949a8aba3",
      "score": 96,
      "scoreNoSim": 96,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "NOCK",
      "token": "0x9b5e262cf9bb04869ab40b19af91d2dc85761722",
      "score": 30,
      "scoreNoSim": 100,
      "predicted": "unsafe",
      "truth": "bad",
      "correct": true,
      "oracleReason": "HONEYPOT DETECTED"
    },
    {
      "symbol": "TIBBIR",
      "token": "0xa4a2e2ca3fbfe21aed83471d28b6f65a233c6e00",
      "score": 100,
      "scoreNoSim": 100,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "CTR",
      "token": "0x11030f79109269d796fd0fb956d6244e502757f7",
      "score": 100,
      "scoreNoSim": 100,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "GITLAWB",
      "token": "0x5f980dcfc4c0fa3911554cf5ab288ed0eb13dba3",
      "score": 100,
      "scoreNoSim": 100,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "YAPPR",
      "token": "0x8c3e96713977e61c4180a5f0a6b02fab86fb5ba3",
      "score": 90,
      "scoreNoSim": 90,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    },
    {
      "symbol": "VU",
      "token": "0x511ef9ad5e645e533d15df605b4628e3d0d0ff53",
      "score": 100,
      "scoreNoSim": 100,
      "predicted": "safe",
      "truth": "good",
      "correct": true,
      "oracleReason": "sellable"
    }
  ],
  "notes": [
    "Ground truth from honeypot.is buy/sell simulation — an external buy/sell fork sim, independent of this engine's market-data/GoPlus/owner heuristics.",
    "Each token scored twice: WITH live simulation (metrics) and WITHOUT (metricsNoSim) to show the real lift from the simulation signal vs the static engine.",
    "Universe = blue-chip controls + watchlist + live GeckoTerminal Base discovery + low-liquidity new_pools harvest + published verdict log. All real on-chain addresses; no hardcoded rug list.",
    "Tokens the oracle cannot classify (no liquidity / sim failure / not indexed) are skipped, not guessed."
  ]
}
