// Stable types for the backtest report. Kept separate from backtest.ts because
// backtest.ts is fully regenerated by agent/backtest.ts on every run.
export type BacktestRow = {
  symbol: string
  token: string
  score: number // engine score WITH live simulation (production)
  scoreNoSim: number // engine score WITHOUT simulation (ablation / static engine)
  predicted: "unsafe" | "safe"
  truth: "bad" | "good"
  correct: boolean
  oracleReason: string
}

export type BacktestMetrics = {
  precision: number
  recall: number
  f1: number
  accuracy: number
}

export type BacktestPoint = { threshold: number } & BacktestMetrics

export type BacktestReport = {
  generatedAt: string | null
  oracle: string
  predictionRule: string
  threshold: number
  universe: {
    candidates: number
    labeled: number
    bad: number
    good: number
    skippedUnknown: number
  }
  confusion: { tp: number; fp: number; tn: number; fn: number }
  metrics: BacktestMetrics // WITH simulation (production setting)
  metricsNoSim: BacktestMetrics // WITHOUT simulation (static engine, ablation)
  sweep: BacktestPoint[] // WITH simulation
  rows: BacktestRow[]
  notes: string[]
}
